name: Build font

defaults:
  run:
    shell: bash # Enable bash pipefail option to watch pipe errors

on:
  workflow_dispatch: # Execute manually
    inputs:
      fontFormat:
        type: choice
        description: Font Format
        options:
        - woff2
        - ttf
      fontType:
        type: choice
        description: Font Type
        options:
        - color
        - flat
        - hc
      runsOn:
        type: choice
        description: runs-on
        options:
        - ubuntu-latest
        - macos-latest  # must be set in case of ttf x color. 

jobs:
  display-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Add Inputs as Table
        run: |
          echo "## User Inputs" >> $GITHUB_STEP_SUMMARY
          echo "| Field   | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| **fontFormat** | ${{ inputs.fontFormat }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **fontType** | ${{ inputs.fontType }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **runsOn** | ${{ inputs.runsOn }} |" >> $GITHUB_STEP_SUMMARY
  font-build:
    runs-on: ${{inputs.runsOn}}
    permissions:
      contents: write
    steps:
      # Prepare Python env
      - name: Prepare requirements.txt
        if: hashFiles('**/requirements.txt', '**/pyproject.toml') == ''
        run: |
          touch ./requirements.txt
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip  # Enable cache
      # Checkout this repo codes
      - name: Checkout this repo code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      # Clear dist folder
      - name: Clear dist folder
        run: rm ./dist/* && chmod 777 ./*.sh
      # Build font
      # For ordinary version
      - name: Build font
        run: ./build_${{inputs.fontFormat}}.sh ${{inputs.fontType}}
      # Upload Artifact
      - name: Upload Font
        uses: actions/upload-artifact@v4
        with:
          name: Font
          path: ./dist/*
